Yoonlang/qrcode-shopping

src/components/QrScanner/QrCode.tsx
=> feat: QrScannerBox 구현

src/api.ts, src/components/Manager/Dashboard.tsx, src/components/Manager/DashboardItems.tsx, src/components/Manager/OrderInfo/UserInfoTable.tsx, src/components/Manager/Product/ProductBoard.tsx, src/components/Manager/Product/ProductTable.test.tsx, src/components/Manager/Product/ProductTable.tsx, src/components/Manager/Product/const.ts, src/components/Manager/const.ts, src/const.ts
=> [v1] 컴포넌트 typescript 적용 및 api 버전 대응 (get)

src/components/AppBar.tsx, src/components/UserInfoSubmission/CountrySelect.tsx, src/components/validation.ts
- 국가 input 유효성 검사 코드 수정
- 유효하지 않은 폼 제출 시 스낵바 출력
=> Info 페이지 폼 제출 관련 문제 해결 #193

.eslintrc.json, src/api.ts, src/components/Manager/Dashboard.tsx, src/components/Manager/Menu.tsx, src/components/Manager/OrderInfo/UserBoard.tsx, src/components/Manager/OrderInfo/UserInfoTable.tsx, src/components/Manager/Product/ProductBoard.tsx, src/components/Manager/Product/ProductTable.tsx, src/components/Manager/Product/const.ts, src/components/Manager/const.ts, src/util.ts
+ `"@typescript-eslint/no-unused-vars": "warn"` lint에 다시 추가
+ 휴지통으로 이동 및 영구 삭제 구현
+ overlay를 통해서 fetch 실패 시 처리 구현
``` ts
export const transformUserToSoftDeleteFormat = (user: OrdererInfo): string => {
const { metadata, userId, ...rest } = user;
const transformedData = {
...rest,
folderId: USER_TRASH_CAN,
submissionTime: metadata.submissionTime,
};
return JSON.stringify(transformedData);
};
```
위 코드에서 userId가 쓰이지 않아서 에러 발생.
이를 해결하려면 
``` ts
export const transformUserToSoftDeleteFormat = (user: OrdererInfo): string => {
const transformedData = {
...user,
folderId: USER_TRASH_CAN,
submissionTime: user.metadata.submissionTime,
};
// userId와 metadata를 제외한 새로운 객체 생성
const finalData = Object.fromEntries(
Object.entries(transformedData).filter(([key]) => key !== 'userId' && key !== 'metadata')
); …
```
=> 데이터 휴지통으로 이동 및 영구 삭제 구현

.eslintrc.json, src/api.ts, src/components/Confirm.tsx, src/components/Manager/Dashboard.tsx, src/components/Manager/Folder/FolderActionModal.tsx, src/components/Manager/Folder/FolderCreationModal.tsx, src/components/Manager/Menu.tsx, src/components/Manager/OrderInfo/UserBoard.tsx, src/components/Manager/OrderInfo/UserInfoTable.tsx, src/components/Manager/Product/ProductBoard.tsx, src/components/Manager/Product/ProductTable.tsx, src/components/Manager/Product/const.ts, src/components/Manager/const.ts, src/const.ts, src/util.ts
+ 폴더 생성, 삭제, 수정에 대한 로직 처리
+ 폴더 삭제 시 경고를 위한 Confirm 컴포넌트 구현
+ API 실패 시 overlay를 통해 Dialog 처리
+ 선택 된 폴더 색깔 변경
+ 폴더 뎁스 추가
=> 매니저 페이지 폴더 구조 part 2

package-lock.json, package.json, public/svg/x.svg, src/components/AppBar.tsx, src/components/Icons.tsx, src/components/Info.tsx, src/components/LanguageSelector.tsx, src/components/Manager/Dashboard.tsx, src/components/Manager/DashboardItems.tsx, src/components/Manager/OrderInfo/UserBoard.tsx, src/components/Manager/OrderInfo/UserInfoTable.tsx, src/components/Manager/Product/ProductBoard.tsx, src/components/Manager/Product/ProductTable.tsx, src/components/MessageDialog.tsx, src/components/MessageSnackBar.tsx, src/components/QrScanner/QrCode.tsx, src/components/SplashScreen.tsx, src/components/ToBuyList/styled.ts, src/components/UserInfoSubmission/CountrySelect.tsx, src/components/UserInfoSubmission/FormItems.tsx, src/components/pages/QrScannerPage.tsx, src/components/pages/SubmissionCompletePage.tsx, src/components/pages/ToBuyListPage.tsx, src/styles/global.tsx
- Splash Screen 수정
- 스타일 수정 및 페이드 효과 추가
- SessionStorage 관련 코드 삭제
- 페이지 로드 시 FoUC 문제 해결
- 모든 styled-component를 @emotion/styled로 교체
=> Splash Screen 스타일 수정 #197

src/api.ts, src/components/Manager/Product/ProductBoard.tsx, src/components/Manager/Product/ProductTable.tsx, src/components/Manager/Product/util.ts, src/components/Manager/User/UserBoard.tsx, src/components/Manager/User/UserDetailModal.tsx, src/components/Manager/User/UserTable.tsx, src/components/Manager/User/const.ts, src/components/Manager/User/util.ts, src/const.ts, src/util.ts
+ 비고란 구현
+ 테이블 열들 재정비
+ "전체" 에서는 폴더명, 폴더 ID도 볼 수 있게 처리
Detail 모달창 다른 데이터들 구현
=> 테이블 추가 요구사항 구현

src/components/Manager/Product/ProductBoard.tsx, src/components/Manager/Product/ProductCreateModal.tsx, src/components/Manager/Product/ProductEditModal.tsx
이제 product 특정 폴더에서 데이터 생성 시 default 폴더에서 생성되지않고 해당 폴더에서 생성 됨
+ Edit Modal, Create Modal에서 folderID input 추가
=> 특정 폴더에서 데이터 처리 적용

src/api.ts, src/components/Manager/Product/ProductBoard.tsx, src/components/Manager/Product/ProductCreateModal.tsx, src/components/Manager/Product/ProductEditModal.tsx
제품 생성 및 수정에 대해 테이블 렌더링, 모달 렌더링 처리 완료
=> api 호출 후 데이터 갱신 처리

public/svg/x.svg, src/components/LanguageSelector.tsx, src/components/Manager/DashboardItems.tsx, src/styles/global.tsx
- X 아이콘 색상 변경
- LanguageSelector 버튼 hover 시 background-color 변경
=> LanguageSelector 스타일 수정 #220

src/app/[locale]/page.tsx, src/components/AppBar.tsx, src/hooks/useInitialFormikValues.ts, src/locales/en/common.json, src/locales/ko/common.json, src/locales/zh/common.json
+ User page에 OverlayProvider 도입
=> feat: User Submit 실패 시 처리

package-lock.json, package.json, src/api.ts, src/components/Manager/Folder/DataFolderReassignModal.tsx, src/components/Manager/Folder/FolderActionModal.tsx, src/components/Manager/Folder/FolderCreationModal.tsx, src/components/Manager/Menu.tsx, src/components/Manager/Product/ExcelProductCreateModal.tsx, src/components/Manager/Product/ExcelProductTableModal.tsx, src/components/Manager/Product/ProductBoard.tsx, src/components/Manager/Product/ProductDetailModal.tsx, src/components/Manager/Product/const.ts, src/components/Manager/Product/util.ts, src/components/Manager/User/UserBoard.tsx, src/components/Manager/User/UserDetailModal.tsx
+ 이번에 구현한 핵심 컴포넌트 : `ExcelProductTableModal`, `ExcelProductCreateModal`
+ Excel 파일 제품 type, schema 구현
+ fetch 실패 시 Dialog 처리
+ products/batch API는 multiparts/form-data가 아닌 application/json이기에 json으로 처리
[제품입력양식_JOJO_240801-4.xlsx](https://github.com/user-attachments/files/16486941/_JOJO_240801-4.xlsx)
테스트 시 휴지통 영구 삭제까지 해주세요
=> 엑셀 파일 데이터로 Product 생성 모달 구현

src/api.ts, src/components/Manager/User/UserBoard.tsx, src/components/Manager/User/UserTextActionModal.tsx
=> 매니저 설정 텍스트 처리 모달 구현

src/components/Manager/User/UserBoard.tsx, src/components/Manager/User/UserCopyModal.tsx, src/components/Manager/User/util.ts, src/locales/ja/common.json
=> User 테이블 선택 항목 복사 기능 구현 #226

src/components/MessageSnackBar.tsx, src/locales/ja/common.json, src/locales/zh/common.json
+ 각 언어별 문장에 맞게 폰트 사이즈 조절
+ scanned일 시에만 별도로 정방형 스낵바 스타일 구현
=> 스캔 완료에 대한 스낵바 별도 로직 구현 #246

src/components/Manager/Product/ProductTable.tsx, src/components/Manager/Product/const.ts, src/components/Manager/Product/util.ts
=> feat: ProductTable 열 처리 #250

package-lock.json, package.json, src/components/AppBar.tsx, src/components/CounselingIntakeForm.tsx, src/components/Manager/User/UserBoard.tsx, src/components/Manager/User/const.ts, src/components/pages/SubmissionCompletePage.tsx, src/components/pages/WeChatFriendGuidePage.tsx, src/hooks/useInitialFormikValues.ts, src/locales/en/common.json, src/locales/ja/common.json, src/locales/ko/common.json, src/locales/zh/common.json, src/recoil/atoms/userIdState.ts
- PDF 내부에 User ID 데이터 추가
- Manager 페이지 PDF 다운 기능 구현
- PDF 스타일 수정
=> PDF 관련 추가 요구사항 구현 #235

src/components/Manager/Menu.tsx, src/components/Manager/User/UserDetailModal.tsx, src/components/Manager/User/util.ts, src/locales/en/common.json, src/locales/ja/common.json, src/locales/ko/common.json, src/locales/zh/common.json, src/recoil/atoms/fetchedItemListState.ts
+ 폴더 생성이 순서대로 안 되던 문제는 폴더 생성 시간 기준을 "YYYY-MM-DD HH:mm"으로 둬서 분 단위가 같으면 다른 로직으로 우선순위가 잡히기 때문에 발생. 이를 백엔드 측에서 "YYYY-MM-DD HH:mm:ss"로 변경했기에 프론트 측 코드엔 변화 없음
=> 자잘한 개선사항들 처리 #258

src/app/[locale]/manager/page.tsx, src/components/AppBar.tsx, src/components/CounselingIntakeForm.tsx, src/components/Manager/User/UserBoard.tsx, src/const.ts, src/hooks/useInitialFormikValues.ts
| 유저 언어 설정: 일어 | 유저 언어 설정: 한국어 |
|--------|----------------------------|
| ![일어](https://github.com/user-attachments/assets/ab0193ce-5ea4-4820-ab71-ddf80f238bab) | ![한국어](https://github.com/user-attachments/assets/4ba91e81-7671-4084-a163-2c20c8276d47) |
=> 매니저 TranslationsProvider 적용 및 user lang pdf 처리 #260

.husky/commit-msg, commitlint.config.js, package-lock.json, package.json, tsconfig.json
커밋 컨벤션을 위해 commitlint를 적용했음
- 커밋 시 commitlint를 통해 커밋메시지 검사 과정이 생김
- custom rule을 통해서 {type}: ~~ 형태로 메세지 형식을 강요했음
=> commitlint 적용 #278

.eslintrc.json, src/components/common/TranslationsProvider.js, src/components/manager/Dashboard.tsx, src/components/manager/folder/DataFolderReassignModal.tsx, src/components/manager/product/ProductBoard.tsx, src/components/manager/product/ProductCreateModal.tsx, src/components/manager/product/ProductEditModal.tsx, src/components/manager/user/UserBoard.tsx, src/components/manager/user/UserTextActionModal.tsx, src/components/pages/ManagerPage.tsx, src/components/user/qrScanner/QrCode.tsx, src/components/user/userSubmission/CompanyAddress.tsx, src/components/user/userSubmission/CountrySelect.tsx, src/components/user/userSubmission/ShippingAddress.tsx
no-floating-promises ESLint 경고에 대해 전부 처리했습니다.
- Formik에서 쓰이던 setValue 등에 void 처리
- useEffect 내에서 쓰이는 Promise 반환하는 함수들에 void 명시
void를 붙이게되면 try catch의 catch로 넘어가지 않으니 이를 인지하고 void를 명시해야합니다.
```
const f = async () => {
// ...
throw Error('에러 발생');
};
try {
void f();
} catch (error) {
console.log(error); // not work!
}
// 출처: https://chinsun9.github.io/2022/03/06/js-void-operator/#google_vignette
```
=> ESLint no-floating-promises 해결 및 error로 격상 #290

src/components/common/Icons.tsx, src/components/const.ts, src/components/manager/user/UserBoard.tsx, src/components/pages/UserSubmissionPage.tsx, src/components/user/toBuyList/styled.ts, src/components/user/userSubmission/CountrySelect.tsx, src/components/user/userSubmission/countries.ts
콘솔 로그를 확인할 때 뜨는 자잘한 warning과 error가 불편하여 이들에 대해 해결하고자 하였습니다.
아래 사항을 해결하였습니다.
- Cart 페이지
- “:first-child” is potentially unsafe error
- Info 페이지
- Autocomplete 데이터 형식 invalid warning
- uncontrolled Autocomplete에 대한 default value를 바꿈에 따라 발생하는 error
- Autocomplete unique key prop error
추가적으로 로컬 스토리지가 제대로 초기화되지 않는 문제도 해결했습니다.
`"fix: Autocomplete invalid ..."`와 같이 타입 이후의 subject가 upper-case로 시작하면 커밋이 반려되었습니다.
commitlint 룰을 한 번 더 살펴볼 필요가 있는 것 같습니다.
=> 개발자 도구 warning, error 해결 #292

src/components/manager/Dashboard.tsx, src/components/manager/DashboardItems.tsx, src/components/manager/Menu.tsx, src/components/manager/util.ts
=> 매니저 메뉴 크기 개선 및 줄임말 삭제 #312

src/components/user/qrScanner/QrCode.test.tsx, src/components/user/qrScanner/QrCode.tsx
- QrCode 테스트 설명을 유저 입장에서 작성
- 실제 코드와 동작 일치하도록 프로그레스 바도 테스트 코드에서 도입
- 기타 any 타입에 대해 수정
이번 feature에서 QR 코드 관련 더 많은 테스트를 도입하려 했으나 유닛 테스트를 하기에는 video 하드웨어를 mock 해야하는 상황입니다. 이를 mock하면서 원하는 추가 테스트를 작성하려면 사실상 전부 mocking을 해야했기에 이를 보류하고 기초적인 일부 개선만 적용했습니다.
=> QrCode 테스트 코드 개선 및 type 도입 #314

cypress/e2e/manager/auth/login.cy.ts, cypress/e2e/manager/manager.cy.ts, cypress/support/commands.ts, cypress/support/index.d.ts, cypress/tsconfig.json, src/components/manager/user/UserBoard.tsx
로그인 시나리오에 대한 테스트 코드를 작성했습니다.
`manager.cy.ts`의 경우 추후 다른 테스트 코드도 추가되었을 때 해당 코드들을 import하여 한꺼번에 테스트하기 위한 파일입니다.
=> E2E 테스트 - 로그인 #316

src/components/manager/product/ExcelProductTableModal.tsx, src/components/manager/product/ProductDetailModal.tsx, src/components/manager/product/const.ts
- 엑셀 테이블 줄 오차 개선
- 제품 수정 모달에서 이미지가 있을 시 vallidation 통과 못하던 문제 해결
- 제품 수정 후 바로 EditModal 들어갈 시 수정 된 제품 표시되도록 개선
=> ProductEditModal, 엑셀 테이블 줄 개선 #328
